version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Packaging Lambda function..."
      - zip -r deployment.zip index.js
      - echo "Uploading new Lambda function code..."
      - aws lambda update-function-code --function-name mylambdafunction-1 --zip-file fileb://deployment.zip
      - echo "Publishing new version..."
      - NEW_VERSION=$(aws lambda publish-version --function-name mylambdafunction-1 --query Version --output text)
      - echo "New Version: $NEW_VERSION"
      - >
        if [ -z "$NEW_VERSION" ] || [ "$NEW_VERSION" == "0" ]; then
          echo "Error publishing new version!";
          exit 1;
        fi
      - echo "Updating alias to new version..."
      - aws lambda update-alias --function-name mylambdafunction-1 --name Prod --function-version "$NEW_VERSION"

artifacts:
  files:
    - deployment.zip
