version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running tests...
      - npm test

  post_build:
    commands:
      - echo Deploying Lambda function...
      - aws lambda update-function-code --function-name mylambdafunction-1 --zip-file fileb://deployment.zip
      - echo Publishing new Lambda version...
      - NEW_VERSION=$(aws lambda publish-version --function-name mylambdafunction-1 --query "Version" --output text)
      - echo New Lambda version: $NEW_VERSION
      - echo "Checking Resilience Hub for errors..."
      - RESILIENCE_STATUS=$(aws resiliencehub describe-app --app-name lambda-1 --query "appStatus" --output text)
      - echo "Resilience Status: $RESILIENCE_STATUS"
      - |
        if [ "$RESILIENCE_STATUS" != "HEALTHY" ]; then
          echo "Error detected in new Lambda version. Rolling back..."
          aws lambda update-alias --function-name mylambdafunction-1 --name PROD --function-version <previous-version>
        fi

artifacts:
  files:
    - deployment.zip
